### ISSUE TITLE
你是如何配置让javacomplete自动读取jar文件的

### ISSUE THREAD

**Issue by wsdjeg** [stirp/.vim#1]
你用vim写java是如何设置的

**Comment by stirp** [comment]
我的snippet似乎没有没有生效，要不就是没有配置呢。

其他的都可以用的，效果跟vim-javacomplete2展示的效果一样（除了cle这也的snippet）

**Comment by wsdjeg** [comment]
我也是新手，感觉vim写JAVA很吃力

**Comment by stirp** [comment]
是很吃力的，因为缺少了很多东西，比如XML支持什么的。如果纯写Java代码用VIM还好，如果用到了各种框架，还是IntelliJ这样的IDE比较好。

我配置这个主要是为了方便偶尔修改代码，合并分支时使用的，IDE的图形界面的Git操作没有命令行功能强大，但是命令行合并的时候不得不用VIMdiff，有了这种配置以后就方便合并了。

**Comment by wsdjeg** [comment]
有一个插件可以显示git差异的,https://github.com/airblade/vim-gitgutter
推荐试试
